---
- name: uninstall nginx and dependencies
  yum:
    name: "{{ CentOS_packages }}"
    state: absent
  when: uninstall_nginx is defined

- name: install nginx and dependencies
  yum:
    name: "{{ CentOS_packages }}"
    state: present
    update_cache: yes
