---
- name: uninstall apt keys for nginx
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: absent
  when: uninstall_nginx is defined

- name: uninstall nginx repo
  file:
    path: /etc/apt/sources.list.d/nginx.list
    state: absent
  when: uninstall_nginx is defined

- name: install apt keys for nginx
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  when: uninstall_nginx is not defined

- name: install nginx repo
  apt_repository:
    filename: nginx
    repo: "{{item}}"
    with_items:
      - 'deb https://nginx.org/packages/mainline/debian/ ""{{ ansible_distribution_release }}" nginx'
      - 'deb-src https://nginx.org/packages/mainline/debian/ "{{ ansible_distribution_release }}" nginx'
    when: uninstall_nginx is not defined
