---
- name: uninstall nginx and dependencies
  apt:
    name: "{{ Debian_packages }}"
    state: absent
  when: uninstall_nginx is defined

- name: install nginx and dependencies
  apt:
    name: "{{ Debian_packages }}"
    state: present
    update_cache: yes

