---
- name: checking for supported distribution
  fail:
    msg: unsupported distribution {{ ansible_distribution }} this only supports CentOS or Debian
  when: (ansible_distribution != "CentOS") or (ansible_distribution != "Debian")

- name: install nginx repo
  include: "{{ ansible_distribution }}_repo.yml"

- name: install nginx and dependencies
  include: "{{ ansible_distribution }}_packages.yml"

- name: configure nginx
  include: "{{ ansible_distribution }}_config.yml"

- name: start nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: logrotate config for nginx
  copy:
    src: nginx.logrotate
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644
